export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PROFILE_PICTURE = "CHANGE_PROFILE_PICTURE";

// master role
export const GET_ROLE = "GET_ROLE";
export const CREATE_ROLE = "CREATE_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const EXPORT_ROLE = "EXPORT_ROLE";

// master menu access mobile
export const GET_MENU_ACCESS_MOBILE = "GET_MENU_ACCESS_MOBILE";
export const CREATE_MENU_ACCESS_MOBILE = "CREATE_MENU_ACCESS_MOBILE";
export const UPDATE_MENU_ACCESS_MOBILE = "UPDATE_MENU_ACCESS_MOBILE";
export const DELETE_MENU_ACCESS_MOBILE = "DELETE_MENU_ACCESS_MOBILE";
export const EXPORT_MENU_ACCESS_MOBILE = "EXPORT_MENU_ACCESS_MOBILE";
export const GET_MENU_ACCESS_MOBILE_BY_ROLE_ID = "GET_MENU_ACCESS_MOBILE_BY_ROLE_ID";
export const SAVE_MENU_ACCESS_MOBILE_BY_ROLE_ID = "SAVE_MENU_ACCESS_MOBILE_BY_ROLE_ID";
export const EXPORT_MENU_ACCESS_MOBILE_BY_ROLE_ID = "EXPORT_MENU_ACCESS_MOBILE_BY_ROLE_ID";

// master departement user
export const GET_MASTER_DEPARTEMENT_USER = "GET_MASTER_DEPARTEMENT_USER";
export const GET_MASTER_DEPARTEMENT_USER_DROPDOWN = "GET_MASTER_DEPARTEMENT_USER_DROPDOWN";
export const CREATE_MASTER_DEPARTEMENT_USER = "CREATE_MASTER_DEPARTEMENT_USER";
export const UPDATE_MASTER_DEPARTEMENT_USER = "UPDATE_MASTER_DEPARTEMENT_USER";
export const UPDATE_STATUS_MASTER_DEPARTEMENT_USER = "UPDATE_STATUS_MASTER_DEPARTEMENT_USER";
export const DELETE_MASTER_DEPARTEMENT_USER = "DELETE_MASTER_DEPARTEMENT_USER";
export const EXPORT_MASTER_DEPARTEMENT_USER = "EXPORT_MASTER_DEPARTEMENT_USER";

// master shift
export const GET_SHIFT = "GET_SHIFT";
export const GET_SHIFT_DROPDOWN = "GET_SHIFT_DROPDOWN";
export const CREATE_SHIFT = "CREATE_SHIFT";
export const UPDATE_SHIFT = "UPDATE_SHIFT";
export const UPDATE_STATUS_SHIFT = "UPDATE_STATUS_SHIFT";
export const DELETE_SHIFT = "DELETE_SHIFT";
export const EXPORT_SHIFT = "EXPORT_SHIFT";

// master status lapangan
export const GET_STATUS_LAPANGAN = "GET_STATUS_LAPANGAN";
export const GET_STATUS_LAPANGAN_DROPDOWN = "GET_STATUS_LAPANGAN_DROPDOWN";
export const CREATE_STATUS_LAPANGAN = "CREATE_STATUS_LAPANGAN";
export const UPDATE_STATUS_LAPANGAN = "UPDATE_STATUS_LAPANGAN";
export const UPDATE_STATUS_STATUS_LAPANGAN = "UPDATE_STATUS_STATUS_LAPANGAN";
export const DELETE_STATUS_LAPANGAN = "DELETE_STATUS_LAPANGAN";
export const EXPORT_STATUS_LAPANGAN = "EXPORT_STATUS_LAPANGAN";

// master witel
export const GET_WITEL = "GET_WITEL";
export const GET_WITEL_DROPDOWN = "GET_WITEL_DROPDOWN";
export const CREATE_WITEL = "CREATE_WITEL";
export const UPDATE_WITEL = "UPDATE_WITEL";
export const UPDATE_STATUS_WITEL = "UPDATE_STATUS_WITEL";
export const DELETE_WITEL = "DELETE_WITEL";
export const EXPORT_WITEL = "EXPORT_WITEL";

// master menu access
export const GET_MENU_ACCESS = "GET_MENU_ACCESS";
export const SAVE_MENU_ACCESS = "SAVE_MENU_ACCESS";
export const EXPORT_MENU_ACCESS = "EXPORT_MENU_ACCESS";

// master user
export const GET_MASTER_USER = "GET_MASTER_USER";
export const CREATE_MASTER_USER = "CREATE_MASTER_USER";
export const UPDATE_MASTER_USER = "UPDATE_MASTER_USER";
export const DELETE_MASTER_USER = "DELETE_MASTER_USER";
export const EXPORT_MASTER_USER = "EXPORT_MASTER_USER";
export const RESET_PASSWORD_USER = "RESET_PASSWORD_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";

// master job position
export const GET_MASTER_JOB_POSITION = "GET_MASTER_JOB_POSITION";
export const GET_MASTER_JOB_POSITION_DROPDOWN = "GET_MASTER_JOB_POSITION_DROPDOWN";
export const CREATE_MASTER_JOB_POSITION = "CREATE_MASTER_JOB_POSITION";
export const UPDATE_MASTER_JOB_POSITION = "UPDATE_MASTER_JOB_POSITION";
export const UPDATE_STATUS_MASTER_JOB_POSITION = "UPDATE_STATUS_MASTER_JOB_POSITION";
export const DELETE_MASTER_JOB_POSITION = "DELETE_MASTER_JOB_POSITION";
export const EXPORT_MASTER_JOB_POSITION = "EXPORT_MASTER_JOB_POSITION";

// setting latest feature
export const GET_SETTING_LATEST_FEATURE = "GET_SETTING_LATEST_FEATURE";
export const CREATE_SETTING_LATEST_FEATURE = "CREATE_SETTING_LATEST_FEATURE";
export const UPDATE_SETTING_LATEST_FEATURE = "UPDATE_SETTING_LATEST_FEATURE";
export const DELETE_SETTING_LATEST_FEATURE = "DELETE_SETTING_LATEST_FEATURE";
export const EXPORT_SETTING_LATEST_FEATURE = "EXPORT_SETTING_LATEST_FEATURE";

// log activity
export const GET_LOG_ACTIVITY = "GET_LOG_ACTIVITY";
export const DELETE_LOG_ACTIVITY_BY_ID = "DELETE_LOG_ACTIVITY_BY_ID";
export const DELETE_LOG_ACTIVITY_FILTER = "DELETE_LOG_ACTIVITY_FILTER";
export const DOWNLOAD_ACTIVITY_BY_ID = "DOWNLOAD_ACTIVITY_BY_ID";
export const DOWNLOAD_ACTIVITY_FILTER = "DOWNLOAD_ACTIVITY_FILTER";

// log notification
export const GET_LOG_NOTIFICATION = 'GET_LOG_NOTIFICATION'
export const DELETE_LOG_NOTIFICATION_BY_ID = 'DELETE_LOG_NOTIFICATION_BY_ID'
export const DELETE_LOG_NOTIFICATION_FILTER = 'DELETE_LOG_NOTIFICATION_FILTER'
export const DOWNLOAD_NOTIFICATION_BY_ID = 'DOWNLOAD_NOTIFICATION_BY_ID'
export const DOWNLOAD_NOTIFICATION_FILTER = 'DOWNLOAD_NOTIFICATION_FILTER'

// system update
export const GET_SYSTEM_UPDATE = "GET_SYSTEM_UPDATE";

// notifications
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_UNREAD_NOTIFICATIONS = "GET_UNREAD_NOTIFICATIONS";
export const READ_NOTIFICATIONS = "READ_NOTIFICATIONS";
export const ALL_NOTIFICATIONS = "ALL_NOTIFICATIONS";

// Transaction
// Daily Man Power
export const GET_DAILY_MANPOWER             = "GET_DAILY_MANPOWER";
export const GET_DAILY_MANPOWER_DROPDOWN    = "GET_DAILY_MANPOWER_DROPDOWN";
export const CREATE_DAILY_MANPOWER          = "CREATE_DAILY_MANPOWER";
export const IMPORT_DAILY_MANPOWER          = "IMPORT_DAILY_MANPOWER";
export const UPDATE_DAILY_MANPOWER          = "UPDATE_DAILY_MANPOWER";
export const DELETE_DAILY_MANPOWER          = "DELETE_DAILY_MANPOWER";
export const EXPORT_DAILY_MANPOWER          = "EXPORT_DAILY_MANPOWER";

// Report PT3
export const GET_REPORT_PT3             = "GET_REPORT_PT3";
export const GET_REPORT_PT3_DROPDOWN    = "GET_REPORT_PT3_DROPDOWN";
export const CREATE_REPORT_PT3          = "CREATE_REPORT_PT3";
export const IMPORT_REPORT_PT3          = "IMPORT_REPORT_PT3";
export const UPDATE_REPORT_PT3          = "UPDATE_REPORT_PT3";
export const DELETE_REPORT_PT3          = "DELETE_REPORT_PT3";
export const EXPORT_REPORT_PT3          = "EXPORT_REPORT_PT3";